### PR TITLE
Content migration

### LINKED ISSUE #4: Migrate content
Move pages and information from the old site to the new.

### PR DESCRIPTION
**Pull request by nate-double-u**
Migrating content from https://github.com/fluent/fluentbit-website-v3 to the new site.

Branched off of PR https://github.com/fluent/fluent-bit-website/pull/7, but I'm trying to keep the commits atomic so we can cherry pick them if we decide to go another route (ie, not docsy).

Top level/menu items to migrate/link
- [x] Documentation (simple link)
- [x] [Blog](https://6000b42e042b1300072a780e--naughty-kilby-f793cf.netlify.app/blog/)
- [x] [Release notes](https://6000b42e042b1300072a780e--naughty-kilby-f793cf.netlify.app/announcements/)
- [ ] Community
- [x] Github (simple link)
- [ ] Enterprise
- [ ] Download

Deploy preview: https://6000b42e042b1300072a780e--naughty-kilby-f793cf.netlify.app/
(from the branch I'm doing the PR from, since we don't have netlify setup on this repo yet)

Fixes: https://github.com/fluent/fluent-bit-website/issues/4

### CODE REVIEW

**Comment by nate-double-u** [comment]
The [Release Notes](https://6000b42e042b1300072a780e--naughty-kilby-f793cf.netlify.app/announcements/) page currently has some issues around spacing in the header i'm working on.
- [ ] Correct header spacing

**Comment by edsiper** [comment]
ping

**Comment by nate-double-u** [comment]
Hi @edsiper, I was reviewing this project a little while ago and had some questions about how best to proceed: https://cncfservicedesk.atlassian.net/browse/CNCFSD-559

**Comment by nate-double-u** [comment]
Closing as stale (https://cncfservicedesk.atlassian.net/browse/CNCFSD-559 has also been closed)

**Pull request closed without merging**
